package com.mailwave.api.modules.tags.models;

public class MessageTag {

    // TO DO: Implements

}

/*
--Referência para criação do modelo
CREATE SEQUENCE SEQ_MESSAGE_TAGS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_MESSAGE_TAGS (
    MESSAGE_TAG_ID NUMBER PRIMARY KEY,
    MESSAGE_ID NUMBER NOT NULL,
    TAG_ID NUMBER NOT NULL,
    MESSAGE_TYPE VARCHAR2(10) NOT NULL, -- RECEIVED ou SENT
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_RECEIVED_MESSAGES(MESSAGE_ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TBL_TAGS(TAG_ID) ON DELETE CASCADE
);
 */