package com.mailwave.api.modules.received.models;

public class ReceivedMessage {

    //TO DO: Implements

}

/*
--Referência para criação do modelo
CREATE SEQUENCE SEQ_RECEIVED_MESSAGES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_RECEIVED_MESSAGES (
    MESSAGE_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL,
    SENDER VARCHAR2(255) NOT NULL,
    SUBJECT VARCHAR2(255),
    BODY CLOB,
    RECEIVED_AT TIMESTAMP,
    IS_READ NUMBER(1) DEFAULT 0,
    FOLDER_ID NUMBER,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES TBL_ACCOUNTS(ACCOUNT_ID),
    FOREIGN KEY (FOLDER_ID) REFERENCES TBL_FOLDERS(FOLDER_ID)
);
 */