
-- USER
CREATE TABLE TBL_USERS (
    USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EMAIL TEXT NOT NULL,
    PASSWORD_HASH TEXT NOT NULL,
    ACTIVE INTEGER DEFAULT 0 CHECK (ACTIVE BETWEEN 0 AND 1) NOT NULL,
    ROLE TEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME
);

-- ACCOUNTS
CREATE TABLE TBL_ACCOUNTS (
    ACCOUNT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    EMAIL_ADDRESS TEXT NOT NULL,
    PROVIDER TEXT NOT NULL,
    PASSWORD_HASH TEXT NOT NULL,
    INCOMING_SERVER TEXT NOT NULL,
    INCOMING_PORT INTEGER NOT NULL,
    INCOMING_PROTOCOL TEXT NOT NULL,
    OUTGOING_SERVER TEXT NOT NULL,
    OUTGOING_PORT INTEGER NOT NULL,
    USE_SSL INTEGER DEFAULT 0,
    USE_TLS INTEGER DEFAULT 0,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(USER_ID)
);

-- FOLDERS
CREATE TABLE TBL_FOLDERS (
    FOLDER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNT_ID INTEGER NOT NULL,
    FOLDER_NAME TEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES TBL_ACCOUNTS(ACCOUNT_ID)
);

-- TAGS
CREATE TABLE TBL_TAGS (
    TAG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNT_ID INTEGER NOT NULL,
    TAG_NAME TEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES TBL_ACCOUNTS(ACCOUNT_ID)
);

-- RECEIVED MESSAGES
CREATE TABLE TBL_RECEIVED_MESSAGES (
    MESSAGE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNT_ID INTEGER NOT NULL,
    SENDER TEXT NOT NULL,
    SUBJECT TEXT,
    BODY TEXT,
    RECEIVED_AT DATETIME,
    IS_READ INTEGER DEFAULT 0,
    FOLDER_ID INTEGER,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES TBL_ACCOUNTS(ACCOUNT_ID),
    FOREIGN KEY (FOLDER_ID) REFERENCES TBL_FOLDERS(FOLDER_ID)
);

-- SENT MESSAGES
CREATE TABLE TBL_SENT_MESSAGES (
    MESSAGE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNT_ID INTEGER NOT NULL,
    SUBJECT TEXT,
    BODY TEXT,
    SENT_AT DATETIME,
    FOLDER_ID INTEGER,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES TBL_ACCOUNTS(ACCOUNT_ID),
    FOREIGN KEY (FOLDER_ID) REFERENCES TBL_FOLDERS(FOLDER_ID)
);

-- RECIPIENTS
CREATE TABLE TBL_RECIPIENTS (
    RECIPIENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MESSAGE_ID INTEGER NOT NULL,
    RECIPIENT_EMAIL TEXT NOT NULL,
    TYPE TEXT NOT NULL, -- TO, CC, BCC
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_SENT_MESSAGES(MESSAGE_ID)
);

-- RECEIVED ATTACHMENTS
CREATE TABLE TBL_RECEIVED_ATTACHMENTS (
    ATTACHMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MESSAGE_ID INTEGER NOT NULL,
    FILE_NAME TEXT NOT NULL,
    FILE_TYPE TEXT,
    FILE_DATA BLOB,
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_RECEIVED_MESSAGES(MESSAGE_ID)
);

-- SENT ATTACHMENTS
CREATE TABLE TBL_SENT_ATTACHMENTS (
    ATTACHMENT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MESSAGE_ID INTEGER NOT NULL,
    FILE_NAME TEXT NOT NULL,
    FILE_TYPE TEXT,
    FILE_DATA BLOB,
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_SENT_MESSAGES(MESSAGE_ID)
);

-- RECEIVED MESSAGE TAGS
CREATE TABLE TBL_RECEIVED_MESSAGE_TAGS (
    MESSAGE_ID INTEGER NOT NULL,
    TAG_ID INTEGER NOT NULL,
    PRIMARY KEY (MESSAGE_ID, TAG_ID),
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_RECEIVED_MESSAGES(MESSAGE_ID),
    FOREIGN KEY (TAG_ID) REFERENCES TBL_TAGS(TAG_ID)
);

-- SENT MESSAGE TAGS
CREATE TABLE TBL_SENT_MESSAGE_TAGS (
    MESSAGE_ID INTEGER NOT NULL,
    TAG_ID INTEGER NOT NULL,
    PRIMARY KEY (MESSAGE_ID, TAG_ID),
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_SENT_MESSAGES(MESSAGE_ID),
    FOREIGN KEY (TAG_ID) REFERENCES TBL_TAGS(TAG_ID)
);
