---------------------------| USER |---------------------------
CREATE SEQUENCE SEQ_USERS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_USERS (
    USER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

---------------------------| ACCOUNTS |---------------------------
CREATE SEQUENCE SEQ_ACCOUNTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_ACCOUNTS (
    ACCOUNT_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    EMAIL_ADDRESS VARCHAR2(255) NOT NULL,
    PROVIDER VARCHAR2(100) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    INCOMING_SERVER VARCHAR2(255) NOT NULL,
    INCOMING_PORT NUMBER NOT NULL,
    INCOMING_PROTOCOL VARCHAR2(10) NOT NULL,
    OUTGOING_SERVER VARCHAR2(255) NOT NULL,
    OUTGOING_PORT NUMBER NOT NULL,
    USE_SSL NUMBER(1) DEFAULT 0,
    USE_TLS NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES TBL_USERS(USER_ID)
);

---------------------------| FOLDERS |---------------------------
CREATE SEQUENCE SEQ_FOLDERS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_FOLDERS (
    FOLDER_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL,
    FOLDER_NAME VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES TBL_ACCOUNTS(ACCOUNT_ID)
);

---------------------------| LABELS |---------------------------
CREATE SEQUENCE SEQ_LABELS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_LABELS (
    LABEL_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL,
    LABEL_NAME VARCHAR2(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES TBL_ACCOUNTS(ACCOUNT_ID)
);

---------------------------| RECEIVED MESSAGES |---------------------------
CREATE SEQUENCE SEQ_RECEIVED_MESSAGES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_RECEIVED_MESSAGES (
    MESSAGE_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL,
    SENDER VARCHAR2(255) NOT NULL,
    SUBJECT VARCHAR2(255),
    BODY CLOB,
    RECEIVED_AT TIMESTAMP,
    IS_READ NUMBER(1) DEFAULT 0,
    FOLDER_ID NUMBER,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES TBL_ACCOUNTS(ACCOUNT_ID),
    FOREIGN KEY (FOLDER_ID) REFERENCES TBL_FOLDERS(FOLDER_ID)
);

---------------------------| SENT MESSAGES |---------------------------
CREATE SEQUENCE SEQ_SENT_MESSAGES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_SENT_MESSAGES (
    MESSAGE_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL,
    SUBJECT VARCHAR2(255),
    BODY CLOB,
    SENT_AT TIMESTAMP,
    FOLDER_ID NUMBER,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES TBL_ACCOUNTS(ACCOUNT_ID),
    FOREIGN KEY (FOLDER_ID) REFERENCES TBL_FOLDERS(FOLDER_ID)
);

---------------------------| RECIPIENTS |---------------------------
CREATE SEQUENCE SEQ_RECIPIENTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_RECIPIENTS (
    RECIPIENT_ID NUMBER PRIMARY KEY,
    MESSAGE_ID NUMBER NOT NULL,
    RECIPIENT_EMAIL VARCHAR2(255) NOT NULL,
    TYPE VARCHAR2(10) NOT NULL, -- TO, CC, BCC
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_SENT_MESSAGES(MESSAGE_ID)
);

---------------------------| RECEIVED ATTACHMENTS |---------------------------
CREATE SEQUENCE SEQ_RECEIVED_ATTACHMENTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_RECEIVED_ATTACHMENTS (
    ATTACHMENT_ID NUMBER PRIMARY KEY,
    MESSAGE_ID NUMBER NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_TYPE VARCHAR2(50),
    FILE_DATA BLOB,
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_RECEIVED_MESSAGES(MESSAGE_ID)
);

---------------------------| SENT ATTACHMENTS |---------------------------
CREATE SEQUENCE SEQ_SENT_ATTACHMENTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_SENT_ATTACHMENTS (
    ATTACHMENT_ID NUMBER PRIMARY KEY,
    MESSAGE_ID NUMBER NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_TYPE VARCHAR2(50),
    FILE_DATA BLOB,
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_SENT_MESSAGES(MESSAGE_ID)
);

---------------------------| MESSAGE LABELS |---------------------------
CREATE SEQUENCE SEQ_MESSAGE_LABELS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_MESSAGE_LABELS (
    MESSAGE_LABEL_ID NUMBER PRIMARY KEY,
    MESSAGE_ID NUMBER NOT NULL,
    LABEL_ID NUMBER NOT NULL,
    MESSAGE_TYPE VARCHAR2(10) NOT NULL, -- RECEIVED ou SENT
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_RECEIVED_MESSAGES(MESSAGE_ID) ON DELETE CASCADE,
    FOREIGN KEY (LABEL_ID) REFERENCES TBL_LABELS(LABEL_ID) ON DELETE CASCADE
);