package com.mailwave.api.modules.recipient;

public class Recipient {

    //TO DO: Implements

}

/*
--Referência para criação do modelo
CREATE SEQUENCE SEQ_RECIPIENTS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_RECIPIENTS (
    RECIPIENT_ID NUMBER PRIMARY KEY,
    MESSAGE_ID NUMBER NOT NULL,
    RECIPIENT_EMAIL VARCHAR2(255) NOT NULL,
    TYPE VARCHAR2(10) NOT NULL, -- TO, CC, BCC
    FOREIGN KEY (MESSAGE_ID) REFERENCES TBL_SENT_MESSAGES(MESSAGE_ID)
);
 */